### ISSUE TITLE
Support aggregation duty

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1715]
## Problem to be solved

We need to support [aggregation duties](https://blog.obol.tech/committee-aggregations-with-distributed-validators/) (_beacon_committee_aggregations_ & _sync_committee_aggregations_) with every validator client. 

## Proposed solution

The following is a checklist for support for aggregation duties in the following clients:
- [x] [lighthouse](https://github.com/sigp/lighthouse/tree/stable/validator_client)
- [x] [teku](https://github.com/ConsenSys/teku/tree/master/validator)
- [x] [lodestar](https://github.com/ChainSafe/lodestar)
- [x] [nimbus](https://github.com/status-im/nimbus-eth2)
- [ ] [prysm](https://github.com/prysmaticlabs/prysm)
- [ ] [vouch](https://github.com/attestantio/vouch)

### Out of Scope

Note that this is an epic and will span multiple sprints.
