### ISSUE TITLE
Support validator registrations

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1716]
## Problem to be solved

We need to enable validator registrations with charon. See [design doc](https://docs.google.com/document/d/1J9Kv2LNZtJk_4rG88UGs5ngtL7d14suSsnlgZ5KPcKA/edit#).

## Proposed solution

The following is a checklist for support for validator registrations in the following clients:
- [ ] [lighthouse](https://github.com/sigp/lighthouse/tree/stable/validator_client)
- [ ] [teku](https://github.com/ConsenSys/teku/tree/master/validator)
- [ ] [lodestar](https://github.com/ChainSafe/lodestar)
- [ ] [nimbus](https://github.com/status-im/nimbus-eth2)
- [ ] [prysm](https://github.com/prysmaticlabs/prysm)
- [ ] [vouch](https://github.com/attestantio/vouch)

### Out of Scope

Note that this is an epic and will span multiple sprints.

**Comment by KaloyanTanev** [comment]
Done
