### ISSUE TITLE
`herumi_bls` feature flag

### ISSUE THREAD

**Issue by gsora** [ObolNetwork/charon#1743]
# Feature Tracking

**Current status** (opt-in or opt-out): opt-in

**Opt-in feature flag name**: `herumi_bls`

### Feature Description

Switches `tbls/v2` backend implementation from Kryptology to a Herumi-based one.

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [ ] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by thomasheremans** [comment]
Epic
