### ISSUE TITLE
Track builder registrations with tracker

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#2669]
# 🎯 Problem to be solved
We have two types of builder registrations, pre-generated registrations and registrations submitted by VC (using proposer config). Currently, we use `core_bcast_broadcast_total` metric to successful registrations on dashboard alongwith other duties. While we recently introduced these three metrics for better tracking of duties using tracker: `core_tracker_success_duties_total`, `core_tracker_expect_duties_total` and `core_tracker_failed_duties_total`. 
We need to include `builder_registration` duty tracking in tracker so that we can use one set metrics to track all the duties. Tracker will help in analysing/reporting the reason behind the registrations failure.

# 🛠️ Proposed solution
Integrate recaster component to tracker to report `builder_registration` duty success and failures. It should also pass the error to tracker component to analyse the reason behind the failure.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet
